// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvMsUCbVWPukBCskBdG23YtqFgtJrjFOQ',
    appId: '1:29580934456:web:16c58f4fe1b3b20f0c55cd',
    messagingSenderId: '29580934456',
    projectId: 'smartservices-aacff',
    authDomain: 'smartservices-aacff.firebaseapp.com',
    storageBucket: 'smartservices-aacff.firebasestorage.app',
    measurementId: 'G-98MG5PH87F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDh4TkGRfJVWm79LZaooUhkEmk6KxuWtmQ',
    appId: '1:29580934456:android:843f517b671f81790c55cd',
    messagingSenderId: '29580934456',
    projectId: 'smartservices-aacff',
    storageBucket: 'smartservices-aacff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA19C5JkyW1vFNChcnfV3EIl8Ons93iqXI',
    appId: '1:29580934456:ios:d9c6595ad997a9d30c55cd',
    messagingSenderId: '29580934456',
    projectId: 'smartservices-aacff',
    storageBucket: 'smartservices-aacff.firebasestorage.app',
    iosBundleId: 'com.example.smartService',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA19C5JkyW1vFNChcnfV3EIl8Ons93iqXI',
    appId: '1:29580934456:ios:d9c6595ad997a9d30c55cd',
    messagingSenderId: '29580934456',
    projectId: 'smartservices-aacff',
    storageBucket: 'smartservices-aacff.firebasestorage.app',
    iosBundleId: 'com.example.smartService',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvMsUCbVWPukBCskBdG23YtqFgtJrjFOQ',
    appId: '1:29580934456:web:4a513424128b7d990c55cd',
    messagingSenderId: '29580934456',
    projectId: 'smartservices-aacff',
    authDomain: 'smartservices-aacff.firebaseapp.com',
    storageBucket: 'smartservices-aacff.firebasestorage.app',
    measurementId: 'G-5N0C8NKVSP',
  );
}
